FROM hexpm/elixir:1.16.3-erlang-26.2.3-debian-trixie-20251020-slim

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    git \
    curl \
    nodejs \
    npm \
    inotify-tools \
    postgresql-client

WORKDIR /opt/armitage

ENV MIX_ENV=dev
COPY . .

# Ensure deps are fetched before compiling
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get && \
    mix deps.compile && \
    mix compile

CMD ["iex", "-S", "mix", "phx.server"]
