version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: armitage_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db:5432/armitage_dev
      ENABLE_SCHEDULER: true
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/opt/armitage
      - deps:/opt/armitage/deps
      - _build:/opt/armitage/_build
    working_dir: /opt/armitage
    stdin_open: true
    tty: true
    command: ./dev.entry.sh

volumes:
  pgdata_dev:
  deps:
  _build:

